### ISSUE TITLE
Crash after linking to Google Drive

### ISSUE THREAD

**Issue by scoutchen** [mrpdaemon/encdroid#94]
Created a volume in Windows 10. Was able to mount this using Google Drive with EncDroid in Nexus 5x using Android 8.0. When trying to mount it in Huawei Mediapad M3 using Google Drive with Android 7.0 with the same Google User EncDroid crashes. From then on the App cannot bei started any more. Only after deinstallation and installation the App can be started again, but same behaviour when I try to connect to Google Drive again.

Are there any log files I can check?

**Comment by maxbruecken** [comment]
As a workaround you can give EncDroid permissions for contacts (Settings->Apps->EncDroid->Permissions). In Android 6.0 the permission GET_ACCOUNTS was moved into the CONTACTS permission group. Unfortunately EncDroid doesn't request permission for reading accounts and crashes. Android 8.0 ignores GET_ACCOUNTS permission, so EncDroid can read accounts under Android 8.0.
